# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  # DATE:
  #   sh: date +"%d%b%y%R%Z"
  #   -X go.szostok.io/version.buildDate={{.Date}}
  DIRTY_VERSION:
    sh: git describe --tags --abbrev=12 --dirty --broken
  BIN_NAME:
    sh: basename $(pwd)
  GOOS:
    sh: go env GOOS
  GOARCH:
    sh: go env GOARCH
  GOHOST: "GOOS={{.GOOS}} GOARCH={{.GOARCH}} go"
  LDFLAGS: |
    -s -w
    -X go.szostok.io/version.version={{.DIRTY_VERSION}}

env:
  CGO_ENABLED: "0"

tasks:
  # TODO: add default task
  default:
    cmds:
      - task: clean

  install:
    desc: Install the binary
    aliases: [i]
    cmds:
      - "{{.GOHOST}} install -ldflags '{{.LDFLAGS}}' ."

  mod:
    desc: Downloads and tidy Go modules
    cmds:
      - go mod download
      - go mod tidy

  clean:
    desc: Cleans temp files and folders
    cmds:
      - rm -rf ./dist/
      - rm -rf ./bin/

  build:
    desc: Build the binary
    deps: [clean]
    cmds:
      - "{{.GOHOST}} build -ldflags '{{.LDFLAGS}}' -o {{.BIN_NAME}}"
      - mkdir -p bin
      - mv {{.BIN_NAME}} bin/

  build-snapshot:
    desc: Build a snapshot with goreleaser
    deps: [clean]
    cmds:
      - goreleaser --snapshot

  changelog:
    desc: Generate changelog
    cmds:
      - git-chglog --next-tag {{.VERSION}} -o CHANGELOG.md

  release:
    desc: Release a new tag
    deps: [build, changelog]
    cmds:
      - git add CHANGELOG.md
      - git commit -m "{{.GIT_CHORE}} update changelog for {{.VERSION}}"
      - git tag {{.VERSION}}
      - git push origin main {{.VERSION}}
    vars:
      GIT_CHORE: "chore:"

  # TODO: add test task
  # test:
